openapi: 3.0.0
info:
  title: 'Space Flight News API'
  version: '0.1'
paths:
  /api/articles:
    get:
      tags:
        - articles
      summary: 'Retorna uma lista de artigos'
      description: 'Retorna um objeto de artigos'
      operationId: 93ded9e31119e6bbb22455c72ef97f19
      parameters:
        -
          name: paginate
          in: query
          description: 'Número de artigos por paginação'
          required: false
          schema:
            type: integer
            default: 300
            maximum: 1000
            minimum: 1
      responses:
        '200':
          description: 'A list with articles'
          content:
            application/json:
              schema: {  }
    post:
      tags:
        - articles
      summary: 'Cria um novo artigo'
      description: 'Cria um novo artigo'
      operationId: 75bdc5f953261e6f34852386c9b522c0
      parameters:
        -
          name: featured
          in: query
          required: false
          schema:
            type: boolean
            default: false
        -
          name: title
          in: query
          required: true
          schema:
            type: string
        -
          name: url
          in: query
          required: true
          schema:
            type: string
        -
          name: imageUrl
          in: query
          required: true
          schema:
            type: string
        -
          name: newSite
          in: query
          required: true
          schema:
            type: string
        -
          name: summary
          in: query
          required: false
          schema:
            type: string
        -
          name: publishedAt
          in: query
          required: false
          schema:
            type: string
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema: {  }
        '422':
          description: 'Faltando dados'
  '/api/articles/{id}':
    get:
      tags:
        - articles
      summary: 'Retorna um artigo pelo ID'
      description: 'Retorna um artigo pelo ID'
      operationId: a85697b2464e9aaa3f9980a83edbef88
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {  }
        '404':
          description: 'Não encontrado'
    put:
      tags:
        - articles
      summary: 'Atualiza um artigo'
      description: 'Atualiza um artigo'
      operationId: beb39fc2f8d02c16b41438aadbd9ba03
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
        -
          name: featured
          in: query
          required: false
          schema:
            type: boolean
            default: false
        -
          name: title
          in: query
          required: true
          schema:
            type: string
        -
          name: url
          in: query
          required: true
          schema:
            type: string
        -
          name: imageUrl
          in: query
          required: true
          schema:
            type: string
        -
          name: newSite
          in: query
          required: true
          schema:
            type: string
        -
          name: summary
          in: query
          required: false
          schema:
            type: string
        -
          name: publishedAt
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {  }
        '422':
          description: 'Faltando dados'
        '404':
          description: 'Não encontrado'
    delete:
      tags:
        - articles
      summary: 'Delete um artigo'
      description: 'Delete um artigo'
      operationId: 804276a4147e577744e158b2ce2b58f8
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: OK
          content:
            application/json:
              schema: {  }
        '404':
          description: 'Não encontrado'
